# Generated by Django 3.2.4 on 2021-07-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store_skins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='Skins')),
            ],
        ),
    ]
